# Generated by Django 4.1.2 on 2022-11-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Subject'),
        ),
    ]
